pdns:
  #build: pdns
  image: mrsrvman/docker-powerdns:4.2
  links:
    - "mysql:mysql"
  ports:
    - "54:53"
    - "54:53/udp"
    - "8088:8081"
  environment:
    - PDNSCONF_API_KEY=a_strong_api_key
    - PDNSCONF_MASTER=yes
    - PDNSCONF_DEFAULT_SOA_NAME=dnsserver.domain.com
    - PDNSCONF_DNSUPDATE=yes
    - SECALLZONES_CRONJOB=yes
    - PDNSCONF_GMYSQL_HOST=mysql
    - PDNSCONF_GMYSQL_DBNAME=pdns
    - PDNSCONF_GMYSQL_USER=pdns
    - PDNSCONF_GMYSQL_PASSWORD=pdnspw
    - PDNSCONF_WEBSERVER_LOGLEVEL=detailed
    - PDNSCONF_LOGLEVEL=6

mysql:
  image: bitnami/mariadb:latest
  environment:
    - MARIADB_ROOT_PASSWORD=mysqlrootpw
    - MARIADB_REPLICATION_MODE=master
    - MARIADB_REPLICATION_USER=repl_user
    - MARIADB_REPLICATION_PASSWORD=repl_password
    - MARIADB_DATABASE=pdns
    - MARIADB_USER=pdns
    - MARIADB_PASSWORD=pdnspw

